safe: true
markdown: kramdown
highlighter: pygments
permalink: /:title.html
relative_permalinks: false

default_theme: sc5
default_width: 792
default_lang: en
default_body_class: list

author:
    name: Varya Stepanova
    url:  http://varya.me
    company:
        name: SC5
        url: http://sc5.io

progress: true
line_numbers: true
